name: Add recurring weekday events to notion

on:
  schedule:
  - cron: "0 0 * * 5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        env:
          NOTION_KEY: ${{secrets.NOTION_KEY}}
          NOTION_DATABASE_ID: ${{secrets.NOTION_DATABASE_ID}}
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run weekdays
